server:
  domain: user
  version: 1.0
  jwtSecret: xxx
  grpcAddress: 127.0.0.1:10001

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: grpc_todolist
  username: root
  password: 1234
  config: charset=utf8mb4&parseTime=True&loc=Local

etcd:
  address: 127.0.0.1:2379

redis:
  ip: 127.0.0.1
  port: 6379
  password: 1234
